config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:registrations]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :projects, only: [:index]
  resources :bio, only: [:index]

end

app/models/ability.rb
# class Ability
#   include CanCan::Ability
#
#   def initialize(user)
#     user ||= User.new
#     if user.admin?
#       can :access, :rails_admin
#     else
#       can :read, :all
#     end
#     # Define abilities for the passed in user here. For example:
#     #
#     #   user ||= User.new # guest user (not logged in)
#     #   if user.admin?
#     #     can :manage, :all
#     #   else
#     #     can :read, :all
#     #   end
#     #
#     # The first argument to `can` is the action you are giving the user
#     # permission to do.
#     # If you pass :manage it will apply to every action. Other common actions
#     # here are :read, :create, :update and :destroy.
#     #
#     # The second argument is the resource the user can perform the action on.
#     # If you pass :all it will apply to every resource. Otherwise pass a Ruby
#     # class of the resource.
#     #
#     # The third argument is an optional hash of conditions to further filter the
#     # objects.
#     # For example, here the user can only update published articles.
#     #
#     #   can :update, Article, :published => true
#     #
#     # See the wiki for details:
#     # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
#   end
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/bio_controller.rb
class BioController < ApplicationController
  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.repos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/app/index.html.erb
<h1>sup dude</h1>

app/views/bio/index.html.erb
<div class="container">
  <h3>About Me</h3>
  <p>Before learning to code I founded a nonprofit in Uganda called   <a href="http://www.maplemicrodevelopment.org">MAPLE Microdevelopment</a> and spent 10 years in the nonprofit sector focused on providing access to education for low-income entrepreneurs. Highlights during this time include designing and teaching business skills curricula, and managing the design and launch of an app.</p>
  <p>After leaving the nonprofit world to work at TalentBin, a tech recruiting search tool,  I led the customer success team and discovered my passion for optimizing workflows and using APIs to create simple, intuitive tools- for example optimizing the onboarding workflow to allow a one-to-many teaching model which improved my team’s weekly throughput by 5x.
  </p>
  <p> As a small startup, TalentBin relied on my team to inform engineering in product design (there was no PM for most of my time) and to train users how to be successful with the tool. This led me to code school, to design applications that facilitate users’ needs and don’t need hours of training.
  </p>
</div>

app/views/home/index.html.erb
<!-- Headline -->
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot valign-wrapper">
      <div class="container">
        <div class="row center">
          <h4 class="header col s12 valign">Junior web developer with background in Product and Customer Success</h4>
          <img src="" alt="">
        </div>
      </div>
    </div>
    <div class="parallax"><%= image_tag "background3.jpg" %></div>
  </div>

<!-- Splash -->
  <div class="container">
    <div class="section">
      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center white-text"><i class="material-icons">code</i></h2>
            <h5 class="center">Full stack experience</h5>
            <ul>
              <li>Responsive Design</li>

              <li>JavaScript: Angular 2, Ember, Node</li>
              <li>Ruby: Rails, Sinatra, Testing</li>
            </ul>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">person_pin</i></h2>
            <h5 class="center">Customer Success experience</h5>

            <p class="light">I led the Customer Success team at TalentBin. I focus on making easy to use features that match user expectations.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">dashboard</i></h2>
            <h5 class="center">Product experience</h5>
            <p class="light">I have PM experience with several product launches both at TalentBin and as a contractor.</p>
          </div>
        </div>
      </div>

    </div>
  </div>

<!-- Selected Projects -->
  <div class="parallax-container valign-wrapper">
    <div class="parallax"><%= image_tag "background2.jpg" %></div>
  </div>

  <div class="container">
    <div class="section">
      <div class="row center">
        <h4 class="header col s12 dark">Selected Projects</h4>
      </div>
          <!--   Icon Section   -->
          <div class="row">
            <div class="col s12 m3">
              <div class="card sticky-action blue-grey darken-2">
                <div class="card-image waves-effect waves-block waves-light">
                  <%= image_tag "kongsweeper.png", class:"activator" %>
                </div>
                <div class="card-content activator">
                  <span class="card-title grey-text text-darken-4">KongSweeper<i class="material-icons right">more_vert</i></span>
                  <p>DonkeyKong Minesweeper</p>
                </div>
                <div class="card-reveal blue-grey darken-2">
                  <span class="card-title grey-text text-darken-4">KongSweeper<i class="material-icons right">close</i></span>
                  <p>DonkeyKong themed Minesweeper like game with sweet custom 8 bit tile graphics. Made with vanilla JavaScript and Bootstrap.</p>
                </div>
                <div class="card-action">
                  <a href="https://github.com/lukeephilips/kongsweeper">Code</a>
                  <a href="https://lukeephilips.github.io/KongSweeper/">Live</a>
                </div>
              </div>
            </div>

            <div class="col s12 m3">
              <div class="card sticky-action">
                <div class="card-image waves-effect waves-block waves-light">
                  <%= image_tag "twit.png", class: "activator" %>
                </div>
                <div class="card-content activator">
                  <span class="card-title grey-text text-darken-4">Tweetamir Putin<i class="material-icons right">more_vert</i></span>
                  <p>Translate tweets into emojis or Russian.</p>
                </div>
                <div class="card-reveal blue-grey darken-2">
                  <span class="card-title grey-text text-darken-4">Tweetamir Putin<i class="material-icons right">close</i></span>
                  <p>Translate any Twitter feed or user input text into English, Spanish, Japanese, Russian or Emojis. Emoji translations made with a custom matching algorithm. Made with Ruby on Sinatra, using the Twitter and Google Translate APIs, ActiveRecord and Materialize.</p>
                </div>
                <div class="card-action">
                  <a href="https://github.com/lukeephilips/emojify">Code</a>
                  <a href="https://twittamir-putin.herokuapp.com">Live</a>
                </div>
              </div>
            </div>

            <div class="col s12 m3">
              <div class="card sticky-action">
                <div class="card-image waves-effect waves-block waves-light">
                  <%= image_tag "streamsearch cropped.png", class: "activator" %>
                </div>
                <div class="card-content activator">
                  <span class="card-title grey-text text-darken-4">StreamSearch<i class="material-icons right">more_vert</i></span>
                  <p>Browse and search multiple streaming sites at once</p>
                </div>
                <div class="card-reveal blue-grey darken-2">
                  <span class="card-title grey-text text-darken-4">StreamSearch<i class="material-icons right">close</i></span>
                  <p>Search accross Netflix, Amazon, Hulu and HBO GO to find movies that are currently streaming on whichever services you have. Made with Angular 2, Sass, TMDB API, GuideBox API, Firebase, TypeScript.</p>
                </div>
                <div class="card-action">
                  <a href="https://github.com/lukeephilips/blank-and-chill">Code</a>
                  <a href="https://stream-search-a433f.firebaseapp.com">Live</a>
                </div>
              </div>
            </div>
            <div class="col s12 m3">
              <div class="card sticky-action">
                <div class="card-image waves-effect waves-block waves-light">
                  <%= image_tag "valhalla1.png", class: "activator" %>
                </div>
                <div class="card-content activator">
                  <span class="card-title grey-text text-darken-4">VALHALLA<i class="material-icons right">more_vert</i></span>
                  <p>Snowboarding gear ecommerce site</p>
                </div>
                <div class="card-reveal blue-grey darken-2">
                  <span class="card-title grey-text text-darken-4">VALHALLA<i class="material-icons right">close</i></span>
                  <p>Browse the online storefront for gear and pay with a credit card. Made with Ruby on Rails, Ajax, Sass, ActiveRecord, credit card payments with Stripe, authentication with Devise, hosted images with Paperclip and S3.</p>
                </div>
                <div class="card-action">
                  <a href="https://github.com/lukeephilips/valhalla">Code</a>
                  <a href="https://shielded-reef-78123.herokuapp.com">Live</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  <div class="parallax-container valign-wrapper">
    <!-- <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">Comfortable in both the front and back end</h5>
        </div>
      </div>
    </div> -->
    <div class="parallax"><%= image_tag "background1.jpg" %></div>
  </div>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>About Me</h4>
          <p>I am a junior software developer in Portland, OR. I am currently enrolled at Epicodus: a six month, fulltime coding bootcamp focused on JavaScript and Ruby on Rails. <hr>
          I am interested in junior roles at small to medium sized tech companies with good opportunities to learn new skills and move further into backend development.
          See <a href="https://docs.google.com/document/d/1vzZAUKdMr7QKettdcXkmxtvXX_qLqo3tYHcDL0EaLu4/edit?usp=sharing">my resume</a> for more information. </p>
        </div>
      </div>

    </div>
  </div>
<script type="text/javascript">
  $(function(){
    $('.button-collapse').sideNav();
    $('.parallax').parallax();
    $('.scrollspy').scrollSpy();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luke Philips Portfolio</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <div class="navbar-fixed">
    <nav class="blue-grey darken-4" role="navigation">
      <div class="nav-wrapper container">
        <%= link_to 'Luke Philips', root_path, class: 'brand-logo', id: "logo-container" %>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to 'Projects', projects_path %></li>
          <li><%= link_to "Bio", bio_index_path %></li>
          <li><a href="https://docs.google.com/document/d/1vzZAUKdMr7QKettdcXkmxtvXX_qLqo3tYHcDL0EaLu4/pub">Resume</a></li>
          <li><a href="https://www.linkedin.com/in/luke-philips">LinkedIn</a></li>
          <% if user_signed_in? %><li><%= link_to "sign out", destroy_user_session_path, method: 'delete' %></li><% end %>
        </ul>

        <ul id="nav-mobile" class="side-nav">
          <li><%= link_to 'Projects', projects_path %></li>
          <li><%= link_to "Bio", bio_index_path %></li>
          <li><a href="https://docs.google.com/document/d/1vzZAUKdMr7QKettdcXkmxtvXX_qLqo3tYHcDL0EaLu4/pub">Resume</a></li>
          <li><a href="https://www.linkedin.com/in/luke-philips">LinkedIn</a></li>
          <% if user_signed_in? %><li><%= link_to "sign out", destroy_user_session_path, method: 'delete' %></li><% end %>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>
  </div>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer class="page-footer blue-grey darken-4">
    <div class="footer-copyright">
      <div class="container">
        <div class="right">
          <%= link_to image_tag("linkedin.png", class: "link-icon"), "https://www.linkedin.com/in/luke-philips" %>
          <%= link_to image_tag("github.png", class: "link-icon"), "http://www.github.com/lukeephilips" %>
        </div>
      </div>
  </footer>
  </body>
</html>

app/views/projects/index.html.erb
<div class="container row">
  <div class="col s6">
    <h3>Check out my repos on GitHub</h3>
    <hr>
    <br>
    <% @projects.each do |project| %>
      <h5>Name: <%= link_to project['name'], project['html_url'] %></h5>
      <p>Description: <%= project['description'] %></p>
      <br>
      <hr>
    <% end %>
  </div>
</div>